import express from "express";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import path from "path";
import logger from "./middleware/logger";
import indexRouter from "./routes";
import authRoutes from "./routes/authRoutes";
import userRoutes from "./routes/userRoutes";
import adminRoutes from "./routes/adminRoutes";
import categoryRoutes from "./routes/categoryRoutes";
import statsRoutes from "./routes/statsRoutes";
import reviewRoutes from "./routes/reviewRoutes";
import searchRoutes from "./routes/searchRoutes";
import fileRoutes from "./routes/fileRoutes";
import favoritesRoutes from "./routes/favoritesRoutes";
import requestRoutes from "./routes/requestRoutes";
import errorHandler from "./middleware/errorHandler";
import providerRoutes from "./routes/providerRoutes";
const app = express();
const generalLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 100 });
const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 20 });
app.use(helmet({ crossOriginResourcePolicy: { policy: "cross-origin" } }));
app.use(logger);
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, "../screens")));
app.use(express.static("public"));
app.use("/", indexRouter);
app.use("/api", generalLimiter);
app.use("/api/auth", authLimiter, authRoutes);
app.use("/api/users", userRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/categories", categoryRoutes);
app.use("/api/admin/stats", statsRoutes);
app.use("/api/reviews", reviewRoutes);
app.use("/api/search", searchRoutes);
app.use("/api/file", fileRoutes);
app.use("/api/favorites", favoritesRoutes);
app.use("/api/requests", requestRoutes);
app.use("/api/providers", providerRoutes);
app.use(errorHandler);

export default app;